USE MASTER
Go

DROP DATABASE IF EXISTS prs
GO

CREATE DATABASE prs_capstone

USE prs_capstone;


CREATE TABLE	Users
(
Id				INT					NOT NULL	IDENTITY PRIMARY KEY,
Username		NVARCHAR(30)		NOT NULL	UNIQUE,
Password		NVARCHAR(30)		NOT NULL,
Firstname		NVARCHAR(30)		NOT NULL,
Lastname		NVARCHAR(30)		NOT NULL,
Phone			VARCHAR(12)			NULL,
Email			VARCHAR(255)		NULL,
IsReviewer		BIT					NOT NULL,
IsAdmin			BIT					NOT NULL
);

CREATE TABLE Vendor
(
Id			INT				NOT NULL	IDENTITY PRIMARY KEY,
Code		VARCHAR(30)		NOT NULL	UNIQUE,
Name		VARCHAR(30)		NOT NULL,
Address		VARCHAR(30)		NOT NULL,
City		VARCHAR(30)		NOT NULL,
State		VARCHAR(2)		NOT NULL,
Zip			VARCHAR(5)		NOT NULL,
Phone		VARCHAR(12)		NOT NULL,
Email		VARCHAR(255)	NOT NULL
);


CREATE TABLE Product
(
Id			INT					NOT NULL	IDENTITY PRIMARY KEY,
PartNbr		VARCHAR(30)			NOT NULL,
Name		VARCHAR(30)			NOT NULL,
Price		DECIMAL(11,2)		NOT NULL,
Unit		VARCHAR(30)			NOT NULL,
PhotoPath	VARCHAR(255)		NULL,
VendorId	INT					NOT NULL	REFERENCES Vendor(Id)
);

CREATE TABLE Request
(
Id				INT				NOT NULL	IDENTITY PRIMARY KEY,
Description		VARCHAR(80)		NOT NULL,
Justification	VARCHAR(80)		NULL,
RejectionReason	VARCHAR(80)		NOT NULL,
DeliveryMode	VARCHAR(20)		NOT NULL	DEFAULT 'PICKUP',	
SubmittedDate	DATE			NOT NULL	DEFAULT GETDATE(),
DateNeeded		DATE			NOT NULL,
Status			VARCHAR(10)		NOT NULL	DEFAULT 'NEW',
Total			DECIMAL (11,2)	NOT NULL	DEFAULT 0,
UserId			INT				NOT NULL	REFERENCES Users (Id)
);

CREATE TABLE RequestLine
(
Id				INT		NOT NULL	IDENTITY PRIMARY KEY,
RequestId		INT		NOT NULL	REFERENCES RequestLine (Id),
ProductId		INT		NOT NULL	REFERENCES Product (Id),
Quantity		INT		NOT NULL	DEFAULT 1
);